---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: synop
spec:
  selector:
    matchLabels:
      app: synop
  template:
    metadata:
      labels:
        app: synop
    spec:
      serviceAccountName: synop
      containers:
      - image: registry.gitlab.com/checkelmann/synop:v0.0.2
        name: synop
        env:
          - name: DT_TENANT
            valueFrom:
                secretKeyRef:
                  name: synop-credentials
                  key: DT_TENANT
          - name: DT_API_TOKEN
            valueFrom:
                secretKeyRef:
                  name: synop-credentials
                  key: DT_API_TOKEN
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: synop-role
rules:
  - apiGroups:
      - ""
      - "extensions"
      - "route.openshift.io"
      - "networking.k8s.io"
    resources:
      - ingresses
      - ingresses/status
      - routes
    verbs:
      - list
      - get
      - update
      - patch
      - watch
      - delete
  - apiGroups:
      - ""
    resources:
      - services
      - pods
    verbs:
      - list
      - get
      - watch
  - apiGroups: [events.k8s.io]
    resources: [events]
    verbs: [create]
  - apiGroups: [""]
    resources: [events]
    verbs: [create]      
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: synop-role-binding
roleRef:
  kind: ClusterRole
  name: synop-role
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: ServiceAccount
  name: synop
  namespace: default
---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: synop   
  name: synop
