{{- if .Values.autoscale.enabled -}}
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "application.fullname" . }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "application.fullname" . }}
  minReplicas: {{ .Values.autoscale.minReplicas }}
  maxReplicas: {{ .Values.autoscale.maxReplicas }}
  targetCPUUtilizationPercentage: {{ .Values.autoscale.targetCPUUtilizationPercentage }}
{{- end }}