{{- $fullName := include "application.fullname" . -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    app.gitlab.com/app: {{ .Values.ci_project_path_slug }}
    app.gitlab.com/env: {{ .Values.ci_environment_slug }}
  name: {{ include "application.fullname" . }}
  labels:
{{ include "application.labels" . | indent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "application.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:    
    metadata:
      annotations:
        app.gitlab.com/env: {{ .Values.ci_environment_slug }}
        app.gitlab.com/app: {{ .Values.ci_project_path_slug }}
      labels:
        app.kubernetes.io/name: {{ include "application.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}        
    spec:
      {{- if .Values.persistentVolume.enabled }}    
      volumes:
      {{ range $data := .Values.persistentVolume.volumes -}}
      - name: {{ $data.volumeName }}
        persistentVolumeClaim:
          claimName: {{ $fullName }}-{{ $data.volumeName }}
      {{- end -}}      
      {{- end -}}    
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}          
          env:
            - name: DT_CUSTOM_PROP              
              value: "keptn_project={{ .Values.keptn_project }} keptn_service={{ .Values.keptn_service }} keptn_stage={{ .Values.ci_environment_slug }} keptn_deployment=direct environment={{ .Values.ci_environment_slug }} app={{ include "application.name" . }} DEPLOYMENT_GROUP_NAME={{ include "application.name" . }}-{{ .Values.ci_environment_slug }} VERSION={{ .Values.image.tag }} DEPLOYMENT_ID={{ .Values.ci_job_id }}"
          {{- if .Values.persistentVolume.enabled }}
          volumeMounts:
          {{ range $data := .Values.persistentVolume.volumes -}}
          - name: {{ $data.volumeName }}
            mountPath: {{ $data.mount }}             
          {{ end -}}      
          {{- end }}          
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          {{- toYaml .Values.probes | nindent 10 -}}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
