{{- if .Values.ingress.enabled -}}
{{- $fullName := include "application.fullname" . -}}
{{- $servicePort := .Values.service.port -}}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ $fullName }}
  annotations:
    ingress.kubernetes.io/whitelist-x-forwarded-for: "true"
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internet-facing
    synops/create: "true"
    synops/endpoint: "/service/ping"
    synops/synthetic.location: "private"
  labels:
{{ include "application.labels" . | indent 4 }}
spec:
  rules:
    - http:
        paths: 
          - path: /*
            backend:
              serviceName: {{ include "application.fullname" . }}
              servicePort: {{ .Values.service.port }}
{{- end }}
