{{- if .Values.ingress.enabled -}}
{{- $fullName := include "application.fullname" . -}}
{{- $servicePort := .Values.service.port -}}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ $fullName }}
  annotations:
    ingress.kubernetes.io/whitelist-x-forwarded-for: "true"
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internet-facing
    synop/create: "true"
    synop/endpoint: "/service/ping"
    synop/synthetic.location: "private"
    synop/synthetic.tags: "opa,oma"
    synop/synthetic.frequencyMin: "10"
  labels:
{{ include "application.labels" . | indent 4 }}
spec:
  rules:
    - http:
        paths: 
          - path: /*
            backend:
              serviceName: {{ include "application.fullname" . }}
              servicePort: {{ .Values.service.port }}
{{- end }}
