dt_create_deployment_event:
  stage: deploy
  image: registry.gitlab.com/checkelmann/cicd-tools:latest
  variables:
      GIT_STRATEGY: none
  script: |
    echo ${APPLICATION_SHORT_NAME}-${CI_ENVIRONMENT_NAME}
    if [ "${CI_COMMIT_TAG}" == "" ]; then
      VERSION=${CI_COMMIT_SHORT_SHA}
    else
      VERSION=${CI_COMMIT_TAG}
    fi
    echo $VERSION

    REMIDATION_ACTION="-rA https://myrevertservice/revert?project=${CI_PROJECT_ID}&service=${APPLICATION_SHORT_NAME}-${CI_ENVIRONMENT_SLUG}&failed_jobid=${CI_JOB_ID}\"
    COMMON_PARAMETER="-I ${DT_TENANT_ID} -A ${DT_API_TOKEN}"
    SPEZIFIC_PARAMETER="-t 'CUSTOM_DEPLOYMENT' -s 'GitLab' -n '${CI_COMMIT_MESSAGE}' -v '${VERSION}' -p '${CI_PROJECT_ID}' ${REMIDATION_ACTION} -cL ${CI_PIPELINE_URL}"
    TAGGING_RULES="-tR 'deployment_group=${APPLICATION_SHORT_NAME}-${CI_ENVIRONMENT_NAME}'"
    CUSTOM_PROPERTIES="-c 'CI_JOB_URL=${CI_JOB_URL},CI_JOB_ID=${CI_JOB_ID},CI_PROJECT_ID=${CI_PROJECT_ID},Commit=${GIT_COMMIT}'"
    COMMAND_PARAMETER="create-deployment-event ${COMMON_PARAMETER} ${SPEZIFIC_PARAMETER} ${CUSTOM_PROPERTIES} ${TAGGING_RULES}"

    echo $COMMAND_PARAMETER
    python /dynapie.py $COMMAND_PARAMETER
