dt_create_deployment_event:
  stage: deploy
  image: registry.gitlab.com/checkelmann/cicd-tools:latest
  variables:
      GIT_STRATEGY: none
  script: |
    export DT_PAYLOAD="
    {
      \"eventType\": \"CUSTOM_DEPLOYMENT\",
      \"attachRules\": {
        \"tagRule\" : {
            \"meTypes\" : \"SERVICE\",
            \"tags\" : [ 
          {
            \"context\": \"CONTEXTLESS\",
            \"key\": \"deployment_group\", 
            \"value\": \"${APPLICATION_SHORT_NAME}-${CI_ENVIRONMENT_NAME}\"
          }
        ]
        }
      },
      \"deploymentName\":\"${CI_COMMIT_MESSAGE}\",
      \"deploymentVersion\":\"${CI_COMMIT_TAG}\",
      \"deploymentProject\":\"${CI_PROJECT_ID}\",
      \"remediationAction\":\"https://myrevertservice/revert?project=${CI_PROJECT_ID}&service=${APPLICATION_SHORT_NAME}-${CI_ENVIRONMENT_SLUG}&failed_jobid=${CI_JOB_ID}\",
      \"ciBackLink\":\"${CI_PIPELINE_URL}\",
      \"source\":\"GitLab\",
      \"customProperties\":{
        \"CI_JOB_URL\": \"${CI_JOB_URL}\",
        \"CI_JOB_ID\": \"${CI_JOB_ID}\",
        \"CI_PROJECT_ID\": \"${CI_PROJECT_ID}\",
        \"Commit\": \"${GIT_COMMIT}\"
      }
    }
    "
    echo $DT_PAYLOAD > payload.tmp
    curl -L -H "Authorization: Api-Token ${DT_API_TOKEN}" -H "Content-Type: application/json" "https://${DT_TENANT_ID}.live.dynatrace.com/api/v1/events" -d @payload.tmp
