---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: chaos-sa
  labels:
    app: chaos-sa
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: chaos-sa
rules:
- apiGroups: ["", "extensions", "apps", "batch", "litmuschaos.io"]
  resources: ["daemonsets", "deployments", "replicasets", "jobs", "pods", "pods/exec","nodes","events", "chaosengines", "chaosexperiments", "chaosresults"]
  verbs: ["*"] 
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: chaos-sa
subjects:
- kind: ServiceAccount
  name: chaos-sa
  namespace: test # App namespace
roleRef:
  kind: ClusterRole
  name: chaos-sa
  apiGroup: rbac.authorization.k8s.io