apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: dynatrace-demo
  region: eu-west-1

nodeGroups:
  - name: ng-1
    instanceType: mixed
    desiredCapacity: 4
    labels: { role: workers }
    instancesDistribution:
      maxPrice: 0.05
      onDemandBaseCapacity: 0
      instanceTypes: ["t3a.large", "t3a.xlarge"]
    iam:
      withAddonPolicies:
        albIngress: true
